### ISSUE TITLE
Absolute bare minimum for client to work ?

### ISSUE THREAD

**Issue by denden4444** [skaarj1989/ArduinoWebSockets#5]
Hi What is the absolute bare minimum of libraries and code the client needs to work on an ESP8266 ?
I saw under the requirements the following were listed : 

    arduino-base64
    CryptoLegacy from arduinolibs, you can grab it from here
    Ethernet "2" for W5500
    UIPEthernet #1 or #2 (the choice is yours) for ENC28j60

In the simple example is spi.h needed ?
`
#include <SPI.h>
`
Thank you 

Den

**Comment by skaarj1989** [comment]
Hi,

arduino-base64 and CryptoLegacy (for SHA1 algorithm) are required for this library to work.

Ofcourse you can provide your own libs for base64 and SHA1, but in this case you have to modify functions: ``generateSecKey()`` and ``encodeSecKey()`` in utility.cpp
