### ISSUE TITLE
Ping counts need reset on terminate

### ISSUE THREAD

**Issue by pangus45** [skaarj1989/ArduinoWebSockets#9]
m_NumPings needs reset on termination, otherwise any time ping causes disconnect, when you reconnect, the first ping will cause it to disconnect again.

```
void WebSocket::terminate() {

    //m_Client.flush();

    m_Client.stop();
    m_eReadyState = WSRS_CLOSED;
    m_NumPings = 0; // add this here
}
```

**Comment by skaarj1989** [comment]
Hi,

Thanks for info, I am working on this and few more features.
